#!/bin/sh
OPT="-ggdb0 -Wall -O3 -fomit-frame-pointer"
#OPT="-ggdb3 -Wall -O0"
gcc $OPT -pipe -o installpkg pkgdb.c untgz.c main.c pkgtools.c sysutils.c `pkg-config --libs --cflags glib-2.0` -lz

#VG="valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --log-file=valgrind.log"

#$VG ./pkgdb

#export LD_PRELOAD="hook.so"
#./pkgdb
#gdb