#/----------------------------------------------------------------------\#
#| spkg - The Unofficial Slackware Linux Package Manager                |#
#|                                      designed by Ondøej Jirman, 2005 |#
#|----------------------------------------------------------------------|#
#|          No copy/usage restrictions are imposed on anybody.          |#
#\----------------------------------------------------------------------/#

testdir = tests

compiled-tests = \
  test-pkgdb-legacy \
  test-filedb-speed \
  test-pkgdb \
  test-pkgtools \
  test-sql-speed \
  test-sql \
  test-untgz \
  test-parsers \
  test-path \
  test-mkdir

test-filedb-speed test-sql-speed: test-files.so

.PHONY: tests
tests: $(compiled-tests)

vpath %.c $(testdir) .build
objs-tests = $(foreach t,$(compiled-tests),.build/$(t).o)

$(compiled-tests): .build/$$@.o .build/libspkg.a
	$(CC) $^ $(LDFLAGS) -o $@

test-files.so: .build/test-files.o
	$(CC) $(LDFLAGS) -shared $^ -o $@

.build/test-files.o: .build/test-files.c

.build/test-files.c:
	( echo "const char* files[] = {" ; \
	  ( cd / ; find usr | head -n 100000 | sed 's/.*/"\0",/' ) ; \
	  echo "}; const unsigned int files_cnt = sizeof(files)/sizeof(files[0]);" \
	) > $@

tests-clean:
	rm -f $(compiled-tests) .build/test-files.c test-files.so
