#!/bin/sh
OPTS="-O2 -march=pentium4 -fomit-frame-pointer -D_GNU_SOURCE `pkg-config --cflags --libs glib-2.0`  -I.."
#gcc -O0 -ggdb3 -o filedb filedb.c ../sys.c -D_GNU_SOURCE `pkg-config --cflags --libs glib-2.0` -I../ || exit
gcc $OPTS -o test-add test-add.c filedb.c ../sys.c || exit
gcc $OPTS -o test-get test-get.c filedb.c ../sys.c || exit
gcc $OPTS -o test-pre test-pre.c filedb.c ../sys.c || exit

exit

rm -rf var
time ./filedb
#dot -Tpng -o index.png index.dot
#rm -f index.dot
