#!/bin/sh
# this script can be used to build static glib library
VER=2.6.5

test -d glib-$VER || \
tar xzf glib-$VER.tar.gz || exit 1
rm -rf glib-build
mkdir glib-build

( cd glib-build
  export CFLAGS="-O2 -march=i486 -mcpu=i686 -fomit-frame-pointer"
  export CXXFLAGS="-O2 -march=i486 -mcpu=i686 -fomit-frame-pointer"
  ../glib-$VER/configure --prefix=/usr -enable-shared=no || exit 1
  make -C glib/libcharset libcharset.la || exit 1
  make -C glib libglib-2.0.la || exit 1
) || exit 1

rm -rf glib
mkdir -p glib/glib
cp -r glib-$VER/glib/*.h glib-build/glibconfig.h glib/glib/
mv glib/glib/glib.h glib/
rm glib/glib/glib-object.h
cp glib-build/glib/.libs/libglib-2.0.a glib/

rm -rf glib-build glib-$VER
