#!/bin/sh -e
# this script can be used to build static glib library
VER=2.10.3
OFLAGS="-ggdb1 -O2 -march=i486 -mtune=i686 -fomit-frame-pointer"
#OFLAGS="-ggdb3 -O0 -DDISABLE_MEM_POOLS"

test -d glib-$VER || \
tar xzf glib-$VER.tar.gz || exit 1
rm -rf glib-build
mkdir glib-build

( cd glib-build
  export CFLAGS="$OFLAGS"
  export CXXFLAGS="$OFLAGS"
  ../glib-$VER/configure --prefix=/usr --enable-shared=no --disable-nls || exit 1
  make -C glib/libcharset libcharset.la || exit 1
  make -C glib libglib-2.0.la || exit 1
) || exit 1

rm -rf glib
mkdir -p glib/glib
cp -r glib-$VER/glib/*.h glib/glib/
cp glib-build/glibconfig.h glib/
mv glib/glib/glib.h glib/
rm glib/glib/glib-object.h
cp glib-build/glib/.libs/libglib-2.0.a glib/

rm -rf glib-build glib-$VER
