#!/bin/sh -e
# this script can be used to build static glib library
VER=1.10.2
OFLAGS="-ggdb1 -O2 -march=i486 -mtune=i686 -fomit-frame-pointer"
#OFLAGS="-ggdb3 -O0"

test -d popt-$VER || \
tar xzf popt-$VER.tar.gz || exit 1
rm -rf popt-build
mkdir popt-build

( cd popt-build
  export CFLAGS="$OFLAGS"
  export CXXFLAGS="$OFLAGS"
  ../popt-$VER/configure --prefix=/usr --enable-shared=no --disable-nls || exit 1
  make
) || exit 1

rm -rf popt
mkdir -p popt

cp -r popt-build/.libs/*.a popt/
cp popt-$VER/popt.h popt/

rm -rf popt-build popt-$VER
