.TH SPKG 8 "April 2005" "spkg"
.SH NAME
spkg \- The Unofficial \fISlackware Linux\fR Package Manager
.SH SYNOPSIS
.B spkg
[\fB-i\fR|\fB--install\fR]
[\fB-d\fR|\fB--remove\fR]
[\fB-u\fR|\fB--upgrade\fR]
[\fB-l\fR|\fB--list\fR]
[\fB-r\fR|\fB--root\fR \fIROOT\fR]
[\fB-n\fR|\fB--dry-run\fR]
[\fB-q\fR|\fB--quiet\fR] 
[\fB-v\fR|\fB--verbose\fR]
[\fIpackages...\fR]
.CM ===========================================================================
.SH DESCRIPTION
\fBspkg\fR is fast and robust tool for package management that is compatible 
with \fISlackware Linux\fR.
.CM ===========================================================================
.SH COMMAND LINE ARGUMENTS
.SS Commands
.TP
\fB-i\fR, \fB--install\fR
Install packages.
.TP
\fB-d\fR, \fB--remove\fR
Remove packages.
.TP
\fB-u\fR, \fB--upgrade\fR
Upgrade packages.
.TP
\fB-l\fR, \fB--list\fR
List packages.
.CM ===========================================================================
.SS Options
.TP
\fB-r\fR | \fB--root=\fIROOT\fR
Set altrernate root directory for package operations. (default: "/")
.TP
\fB-v\fR | \fB--verbose\fR
Increase verbosity level. You may use this option multiple times to get even 
more verbose output.
.TP
\fB-q\fR | \fB--quiet\fR
Set verbosity level to zero. Default verbosity level is 1 (show only warnings).
This option disables warnings. Please note, that error messages can't be disabled.
.TP
\fB-n\fR | \fB--dry-run\fR
Don't modify filesystem or database. This may be useful when used along with -v 
option to check what exactly will given command do.
.TP
\fB--no-fast-symlinks\fR
Spkg by default parses doinst.sh for symlink creation code and removes it from
the script. This improves execution times of doinst.sh. Use this option to
disable such optimizations.
.TP
\fB--no-scripts\fR
Disable postinstallation script.
.CM ===========================================================================
.SS Help
.TP
\fB--usage\fR
Display brief usage message.
.TP
\fB-h\fR, \fB--help\fR
Show this help message.
.TP
\fB-V\fR, \fB--version\fR
Display spkg version.
.CM ===========================================================================
.SH FILES
.IP "var/log/{packages,scripts}"
Package database.
.SH EXAMPLES
.TP
spkg -i <packages>   [--install]
.TP
spkg -dv <packages>  [--remove --verbose]
.TP
spkg -u <packages>   [--upgrade]
.TP
spkg -uvn <packages> [--upgrade --verbose --dry-run]
.SH AUTHOR
Written by Ondrej Jirman, 2005-2006
.TP
Official website: http://spkg.megous.com
.SH BUGS
Bug reports can be sent to <megous@megous.com>.
.SH SEE ALSO
.BR ipkg (8),
.BR rpkg (8),
.BR upkg (8),
.BR lpkg (8),
.BR installpkg (8),
.BR removepkg (8),
.BR upgradepkg (8)
