.TH SPKG 8 "April 2005" "spkg"
.SH NAME
spkg \- The Unofficial \fISlackware Linux\fR Package Manager
.SH SYNOPSIS
.B spkg
[\fB-i\fR|\fB--install\fR] [\fB-s\fR|\fB--sync\fR] 
[\fB-m\fR|\fB--mode\fR \fIMODE\fR] [\fB-r\fR|\fB--root\fR \fIROOT\fR]
[\fB-n\fR|\fB--dry-run\fR] [\fB-q\fR|\fB--quiet\fR] 
[\fB-v\fR|\fB--verbose\fR] [\fIpackages...\fR]
.CM ===========================================================================
.SH DESCRIPTION
\fBspkg\fR is fast and robust tool for package management that is compatible 
with \fISlackware Linux\fR.
.CM ===========================================================================
.SH COMMAND LINE ARGUMENTS
.SS Commands
.TP
\fB-i\fR, \fB--install\fR
Install packages. ([p]aranoid|<n>ormal|[b]rutal)
.TP
\fB-s\fR, \fB--sync\fR
Synchronize databases. (<f>rom-legacy|[t]o-legacy)
.CM ===========================================================================
.SS Options
.TP
\fB-m\fR | \fB--mode=\fIMODE\fR
Set command mode of operation. See particular command for available modes.
.TP
\fB-r\fR | \fB--root=\fIROOT\fR
Set altrernate root directory for package operations. (default: "/")
.TP
\fB-v\fR | \fB--verbose\fR
Increase verbosity level. You may use this option multiple times to get even 
more verbose output.
.TP
\fB-q\fR | \fB--quiet\fR
Set verbosity level to zero. Default verbosity level is 1 (show only warnings).
This option disables warnings. Please note, that error messages can't be disabled.
.TP
\fB-n\fR | \fB--dry-run\fR
Don't modify filesystem or database. This may be useful when used along with -v 
option to check what exactly will given command do.
.TP
\fB--no-fast-symlinks\fR
Spkg by default parses doinst.sh for symlink creation code and removes it from
the script. This improves execution times of doinst.sh. Use this option to
disable such optimizations.
.TP
\fB--no-doinst\fR
Disable postinstallation script.
.CM ===========================================================================
.SS Help
.TP
\fB--usage\fR
Display brief usage message.
.TP
\fB-h\fR, \fB--help\fR
Show this help message.
.TP
\fB-V\fR, \fB--version\fR
Display spkg version.
.CM ===========================================================================
.SH FILES
.IP "var/log/{packages,scripts}"
Legacy package database.
.IP "var/log/spkgdb"
Spkg package database.
.SH EXAMPLES
.TP
spkg -imb <packages>   [--install --mode=brutal]
.TP
spkg -ump <packages>   [--upgrade --mode=paranoid]
.TP
spkg -vr <packages>    [--verbose --remove --mode=normal]
.TP
spkg -vnumb <packages> [--upgrade --verbose --dry-run --mode=brutal]
.TP
spkg -s                [--sync --mode=from-legacy]
.SH AUTHOR
Written by Ondrej Jirman, 2005
.TP
Official website: http://spkg.megous.com
.SH BUGS
Bug reports can be sent to <megous@megous.com>.
.SH SEE ALSO
.BR installpkg (8),
.BR upgradepkg (8),
.BR removepkg (8)
